### ISSUE TITLE
buffering store change events instead of calling stateGetter for every change

### ISSUE THREAD

**Issue by mailaneel** [yahoo/fluxible-addons-react#16]
```js
connectToStores(Component, [StoreA, StoreB, StoreC], function stateGetter(){

})
```

When StoreA, StoreC, StoreC emit change event in span of ```x ms``` current implementation will call ```stateGetter``` 3 times which will render component 3 times.

If we can add a way to buffer events that occur in span of  ``` x ms``` it will only be called once.

In connectToStores.js
```js
_onStoreChange: function onStoreChange() {
    if (this.isMounted()) {
        var self = this;
        if (!this._isBuffering) {
            this._isBuffering = true;
            setTimeout(function() {
                self._isBuffering = false;
                self.setState(self.getStateFromStores());
            }, 1)
        }
    }
}
```

**Comment by mridgway** [comment]
React should already buffer re-renders using `requestAnimationFrame`. Calling state getters should be relatively lightweight since the stores should be doing most of the heavy lifting on dispatches.

**Comment by mailaneel** [comment]
thanks @mridgway i will close this then
