### ISSUE TITLE
allow connectToStores to extend getInitialState with custom object

### ISSUE THREAD

**Issue by mdressman** [yahoo/fluxible-addons-react#17]
I am migrated a large codebase from Fluxible@0.2.x to @latest and stumbling on a few patterns we've got throughout that don't seem easily supported with the new `@connectToStores` HoC.

We occasionally extend the component's initial state with custom properties not coming from `getStateFromStores`.  An example might look like this:

```
getInitialState: function () {
  return _.extend(this.getStateFromStores(), {
    moreInitialState: 0
  });
}
```

After looking at the `connectToStores` code, it does not appear possible. I'd propose something along the lines of:

```
function createComponent(Component, stores, getStateFromStores, customContextTypes, customInitialState) {
    ...
    var StoreConnector = React.createClass({
        ...
        getInitialState: function getInitialState() {
            return objectAssign(this.getStateFromStores(), customInitialState);
        },
```

  I'm happy to open a PR for this, but wanted to check with you before doing the work.

What do you think?

**Comment by mridgway** [comment]
Sorry for not getting to this sooner. Could you handle this state in your component rather than in the higher-order component? It seems like it may not belong in the HoC since that is specifically for getting data from stores.

**Comment by mdressman** [comment]
hmm yes, that makes sense. derp.
