### ISSUE TITLE
FluxibleComponent Usage

### ISSUE THREAD

**Issue by mbfisher** [yahoo/fluxible-addons-react#25]
I'm struggling with how `FluxibleComponent` works. The [documentation](https://github.com/yahoo/fluxible-addons-react/blob/master/docs/api/FluxibleComponent.md) says to do this:

 ```js
class Component extends React.Component {
    constructor(props) {
        super(props);
        this.state = this.getStore(FooStore).getState();
    }
}
Component.contextTypes = {
    getStore: React.PropTypes.func.isRequired,
    executeAction: React.PropTypes.func.isRequired
};
```

* How does `getStore` make it on to `this` in the constructor? The only way I've been able to access the context in the constructor is by receiving it as a second argument after `props`.
* Assuming it's correct to access `[this.]context`, the functions have not been bound to a `FluxContext` in `FluxibleComponent#getChildContext`, meaning `getStore` can't access the dispatcher etc.

Am I missing something?

M

**Comment by mridgway** [comment]
Looks like a type. It should be `this.context.getStore...`. I will update the doc.

The context is bound within `context.getComponentContext()`. Make sure you are passing this in as the context prop instead of Fluxible's `context` directly.

**Comment by mbfisher** [comment]
Thanks, not using `getComponentContext()` was the issue!

M

On Fri, Sep 11, 2015 at 7:14 PM, Michael Ridgway <notifications@github.com>
wrote:

> Looks like a type. It should be this.context.getStore.... I will update
> the doc.
>
> The context is bound within context.getComponentContext(). Make sure you
> are passing this in as the context prop instead of Fluxible's context
> directly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yahoo/fluxible-addons-react/issues/25#issuecomment-139617115>
> .
>



-- 
Mike Fisher

Email: mike@mbfisher.com
Skype: mb_fisher
GitHub: mbfisher
