### ISSUE TITLE
react 0.14.0-rc1

### ISSUE THREAD

**Issue by eriknyk** [yahoo/fluxible-addons-react#28]
Hi,
I can't use fluxible-addons-react with react 0.140.0-rc1 ?

npm ERR! peerinvalid The package react@0.14.0-rc1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer fluxible-addons-react@0.1.8 wants react@0.13.x

**Comment by mridgway** [comment]
Hi @eriknyk,

We are currently updating all of our packages to support React 0.14. Currently master is using React 0.14 but we have not released it on npm yet. You can try installing using Github urls as dependencies in your project for now until we release an RC for fluxible's packages which should be in the next couple of days.

**Comment by growlsworth** [comment]
Looking forward to it. Thanks @mridgway.

**Comment by mridgway** [comment]
An RC release of the Fluxible packages has been released under the `next` tag in npm.

```shell
npm i --save fluxible-addons-react@next
```
