### ISSUE TITLE
connectToStores.js uses Object.assign which is not available in es5 browsers

### ISSUE THREAD

**Issue by YoussefTaghlabi** [yahoo/fluxible-addons-react#31]
connetcToStores line 12 to 14 uses Object.assign which is not available in es5 browsers: 

```javasccript
    var componentContextTypes = Object.assign({
        getStore: React.PropTypes.func.isRequired
    }, customContextTypes);
``` 

We currently have to load a polyfill to add Object.assign support.

**Comment by mridgway** [comment]
Correct. Looks like we missed the note in the README like we have on the Fluxible repo: https://github.com/yahoo/fluxible/tree/master/packages/fluxible#browser-compatibility

**Comment by mridgway** [comment]
Added the note to the readme in https://github.com/yahoo/fluxible-addons-react/commit/a6ece794c788829bb817e7622b0764811def4cf7
