### ISSUE TITLE
peerDependencies error when installing fluxible-addons-react

### ISSUE THREAD

**Issue by commandtab** [yahoo/fluxible-addons-react#5]
I'm attempting to use Fluxible for the first time and plan on using FluxComponent, so I first added fluxible:

    npm install --save fluxible

Then fluxible-addons-react:

    npm install --save fluxible-addons-react

Which results in:

```
npm WARN peerDependencies The peer dependency fluxible@>=0.5.0-alpha.1 included from fluxible-addons-react will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "fluxible-addons-react"
npm ERR! node v0.12.5
npm ERR! npm  v2.12.0
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package fluxible does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer fluxible-addons-react@0.1.4 wants fluxible@>=0.5.0-alpha.1

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/me/Projects/projectname/npm-debug.log
```

Am I doing something wrong?

[Here is the full npm-debug.log](https://gist.githubusercontent.com/commandtab/32b17989be6494b72d06/raw/d9a8f5d3999334a45fd7e8f16ef67c641546bece/fluxible-addons-react-error).

Versions of things:

- OS X 10.10.3
- node 0.12.5 via Homebrew
- npm 2.12.0

Thanks so much!

**Comment by Vijar** [comment]
@commandtab make sure you have the `0.5.0-alpha.1` version of fluxible. You can get it by running `npm install fluxible@next` or `npm install fluxible@0.5.0-alpha.1`.

Since `0.5.0-alpha.1` is an alpha release we didn't tag it as `latest` which is probably why it wasn't automatically installed for you.

**Comment by redonkulus** [comment]
@Vijar is correct. if you run `npm i fluxible@next` first, then the addons package installs correctly.
